<a href="https://colab.research.google.com/github/avinash202006/deep-learning-1/blob/main/Encoder_DECODER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

marks = np.array([[85, 90, 78, 88]])

encoder = np.array([
    [0.5, 0.2],
    [0.4, 0.3],
    [0.3, 0.6],
    [0.2, 0.5]
])

encoded = np.dot(marks, encoder)

decoder = np.array([
    [0.6, 0.4, 0.3, 0.2],
    [0.3, 0.5, 0.6, 0.7]
])

reconstructed = np.dot(encoded, decoder)

print("Original Data:")
print(marks)

print("Encoded Data:")
print(encoded)

print("Reconstructed Data:")
print(np.round(reconstructed, 2))

Original Data:
[[85 90 78 88]]
Encoded Data:
[[119.5 134.8]]
Reconstructed Data:
[[112.14 115.2  116.73 118.26]]
