<a href="https://colab.research.google.com/github/avinash202006/deep-learning-1/blob/main/pixel_value.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from PIL import Image
import numpy as np

# Read image from user
image_path = input("Enter image path: ")

# Open image
img = Image.open(image_path)

# Convert image to NumPy array
pixels = np.array(img)

# Display image information
print("Image Shape:", pixels.shape)

print("\nPixel Values:")
print(pixels)

Enter image path: /download copy.png
Image Shape: (1152, 2048, 4)

Pixel Values:
[[[114 114 114 255]
  [114 114 114 255]
  [114 114 114 255]
  ...
  [114 114 114 255]
  [114 114 114 255]
  [114 114 114 255]]

 [[114 114 114 255]
  [114 114 114 255]
  [114 114 114 255]
  ...
  [114 114 114 255]
  [114 114 114 255]
  [114 114 114 255]]

 [[114 114 114 255]
  [114 114 114 255]
  [114 114 114 255]
  ...
  [114 114 114 255]
  [114 114 114 255]
  [114 114 114 255]]

 ...

 [[114 114 114 255]
  [114 114 114 255]
  [114 114 114 255]
  ...
  [114 114 114 255]
  [114 114 114 255]
  [114 114 114 255]]

 [[114 114 114 255]
  [114 114 114 255]
  [114 114 114 255]
  ...
  [114 114 114 255]
  [114 114 114 255]
  [114 114 114 255]]

 [[114 114 114 255]
  [114 114 114 255]
  [114 114 114 255]
  ...
  [114 114 114 255]
  [114 114 114 255]
  [114 114 114 255]]]
